//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapsDirectionService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocationPoint()
        {
            this.RouteDetail = new HashSet<RouteDetail>();
            this.RouteDetail1 = new HashSet<RouteDetail>();
        }
    
        public int LocationPoinId { get; set; }
        public string Name { get; set; }
        public int Radius { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoInfo { get; set; }
        public string GeoInfoText { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouteDetail> RouteDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouteDetail> RouteDetail1 { get; set; }
    }
}
