//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapsDirectionService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.RouteDetail = new HashSet<RouteDetail>();
        }
    
        public int RouteId { get; set; }
        public string Name { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoInfo { get; set; }
        public string GeoInfoText { get; set; }
        public Nullable<int> DeparturePointId { get; set; }
        public Nullable<int> ArrivalPointId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouteDetail> RouteDetail { get; set; }
    }
}
