//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapsDirectionService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteDetail
    {
        public int RouteDetailId { get; set; }
        public string Name { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoInfo { get; set; }
        public string GeoInfoText { get; set; }
        public Nullable<int> DeparturePointId { get; set; }
        public Nullable<int> ArrivalPointId { get; set; }
        public Nullable<int> RouteId { get; set; }
    
        public virtual LocationPoint LocationPoint { get; set; }
        public virtual LocationPoint LocationPoint1 { get; set; }
        public virtual Route Route { get; set; }
    }
}
