//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapsDirectionService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewRoute
    {
        public int RouteId { get; set; }
        public string Name { get; set; }
        public string GeoInfoText { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
